### ISSUE TITLE
ignore 0pdd and other chatbots

### ISSUE THREAD

**Issue by h1alexbel** [zerocracy/judges-action#217]
How about to add feature for ignoring users, I believe it's needed to prevent conversations like this: https://github.com/objectionary/jeo-maven-plugin/issues/650#issuecomment-2265249581. Would be convenient to maintain some list where architect can configure what are the users/chatbots to ignore:

For instance: ignore-users.z

```text
0pdd
rultor
```

@yegor256 WDYT?

**Comment by yegor256** [comment]
Let's add configuration argument to the plugin:

```
- uses: zerocracy/judges-action@0.0.52
  with:
    options: |
      ignore_bots=0pdd,rultor
```
