### ISSUE TITLE
YAML configuration is too complex

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#345]
Currently, we have to do this:

```
- uses: zerocracy/judges-action@0.0.52
  with:
    token: ${{ secrets.ZEROCRACY_TOKEN }}
    options: |
      github_token=${{ secrets.GITHUB_TOKEN }}
      repositories=...
    factbase: foo.fb
```

Would be nice to allow users to do just this:

```
- uses: zerocracy/judges-action@0.0.52
  with:
    token: ${{ secrets.ZEROCRACY_TOKEN }}
    github_token: ${{ secrets.GITHUB_TOKEN }}
    repositories: ...
    factbase: foo.fb
```

Thus, our plugin must understand most popular options and pass them through to the `options` argument of the `judges` tool.

**Comment by Yegorov** [comment]
@yegor256 Should we support two versions of the options transmission at the same time?
If so, then with the simultaneous filing which options should be more priority, e. g.:
```
- uses: zerocracy/judges-action@0.0.52
  with:
    token: ${{ secrets.ZEROCRACY_TOKEN }}
    options: |
      github_token=${{ secrets.GITHUB_TOKEN }}
      repositories=...
    github_token: ${{ secrets.GITHUB_TOKEN }}
    repositories: ...
    factbase: foo.fb
```
Or the `options` parameter must be completely deleted? (But it will be possible backwards compatibility error)

**Comment by yegor256** [comment]
@Yegorov they should be processed with the following priorities:

```
- uses: zerocracy/judges-action@0.0.52
  with:
    options: |
      repositories= higher
    repositories: lower
```
