### ISSUE TITLE
we don't use proper GitHub fake server

### ISSUE THREAD

**Issue by yegor256** [zerocracy/judges-action#760]
Currently, we stub HTTP requests to GitHub with the help of WebMock. This makes our tests pretty long and ugly. Instead, we can use a fake implementation of GitHub API as a server. Let's try to use this one: https://github.com/h1alexbel/fakehub We can try something else if we find similar solutions.

**Comment by crazyrokr** [comment]
Hello. After researching fakehub, it quickly became clear that it did not cover most of the GitHub APIs used in the project. Therefore, 2 other options were explored:
1. Fixtures
2. VCR

Below is a visual comparison of tests in different implementations
Current (WebMock)
```
def test_overwrite_name_if_user_login_changed
    WebMock.disable_net_connect!
    rate_limit_up
    stub_github('https://api.github.com/user/12', body: { login: 'user22', id: 12, type: 'User' })
    stub_github('https://api.github.com/user/13', body: { login: 'user3', id: 13, type: 'User' })
    stub_github(
      'https://api.github.com/user/14',
      status: 404,
      body: { message: 'Not Found', documentation_url: 'https://docs.github.com/rest', status: '404' }
    )
    fb = Factbase.new
    fb.with(_id: 1, what: 'who-has-name', ...).with(...)
    Time.stub(:now, Time.parse('2025-06-23 22:00:00 UTC')) do
      load_it('who-has-name', fb)
      assert(fb.one?(who: 12, name: 'user22'))
      # ...
    end
  end
```

Test with fixtures
```
  def test_overwrite_name_if_user_login_changed
    WebMock.disable_net_connect!
    rate_limit_up
    stub_github('https://api.github.com/user/12', body: user_fixture(id: 12, login: 'user22'))
    stub_github('https://api.github.com/user/13', body: user_fixture(id: 13, login: 'user3'))
    stub_github('https://api.github.com/user/14', status: 404, body: load_fixture('not_found'))
    fb = Factbase.new
    fb.with(_id: 1, what: 'who-has-name', ...).with(...)
    Time.stub(:now, Time.parse('2025-06-23 22:00:00 UTC')) do
      load_it('who-has-name', fb)
      assert(fb.one?(who: 12, name: 'user22'))
      # ...
    end
  end
```

VCR test
```
  def test_overwrite_name_if_user_login_changed
    VCR.use_cassette('who_has_name/overwrite_name_if_user_login_changed') do
      fb = Factbase.new
      fb.with(_id: 1, what: 'who-has-name', ...).with(...)
      Time.stub(:now, Time.parse('2025-06-23 22:00:00 UTC')) do
        load_it('who-has-name', fb)
        assert(fb.one?(who: 12, name: 'user22'))
        # ...
      end
    end
  end
```
and cassette-file (test/cassettes/who_has_name/overwrite_name_if_user_login_changed.yml)
```
  http_interactions:
  - request:
      method: get
      uri: https://api.github.com/rate_limit
      body:
        string: ''
    response:
      status:
        code: 200
        message: OK
      headers:
        Content-Type: [application/json]
        X-RateLimit-Remaining: ['999']
      body:
        string: '{"rate":{"remaining":1000,"limit":1000}}'
    recorded_at: '2025-01-01T00:00:00.000Z'
  - request:
      method: get
      uri: https://api.github.com/user/12
      body:
        string: ''
    response:
      status:
        code: 200
        message: OK
      headers:
        Content-Type: [application/json]
      body:
        string: '{"login":"user22","id":12,"type":"User"}'
    recorded_at: '2025-01-01T00:00:00.000Z'
```

VCR-test looks better itself but requiring cassette-files will increase the total amount of code.
@yegor256 What do you think about this?
